const articlesData= [
    {
        name: "REMERA TÉRMICA MANGA LARGA ALASKA",
        price: 14500,
        rating: [5],
        brand: "Alaska",
        gender: "female",
        size: "S",
        // shoeSize: 5,
        color: "White",
        // comments: ["Esta campera es una porquería"],
        stock: 5,
        image: "https://universoventura.vteximg.com.br/arquivos/ids/191464-600-600/Remera-Termica-Manga-Larga-Alaska-Mailen-Bamboo-Eco-Series-Mujer-ceniza-AM0105-003.jpg?v=637691475523170000",
        type: "Tshirt",
        active: true,
    }, 
    {
        name: "PANTALONES TERMICOS INTERIOR ANSILTA",
        price: 25300,
        rating: [5],
        brand: "Ansilta",
        gender: "female",
        size: "M",
        // shoeSize: 5,
        color: "black",
        comments: ["Compraría 1000", "Son excelentes"],
        stock: 2,
        image: "https://universoventura.vteximg.com.br/arquivos/ids/173719-600-600/ares-2-w.jpg?v=636689002394070000",
        type: "pant",
        active: true,
    },
    {
        name: "CAMPERA ANSILTA CICLON 2 CICLISMO ROMPEVIENTOS WINDSTOPPER",
        price: 25300,
        rating: [5],
        brand: "Ansilta",
        gender: "male",
        size: "L",
        // shoeSize: 5,
        color: "red",
        comments: ["Es excelente, muy buena calidad"],
        stock: 2,
        image: "https://universoventura.vteximg.com.br/arquivos/ids/186604-600-600/Campera-Ansilta-Ciclon-2-Rompevientos-Windstopper-Hombre-Rojo-141148-400.jpg?v=637471808583400000",
        type: "jacket",
        active: true,
    },
    {
        name: "BUZO MEDIO CIERRE SALOMON POLAR LT",
        price: 25300,
        rating: [1],
        brand: "Salomon",
        gender: "male",
        size: "X",
        // shoeSize: 5,
        color: "black",
        comments: ["Se rompió rápido"],
        stock: 5,
        image: "https://universoventura.vteximg.com.br/arquivos/ids/203548-500-500/Buzo-Medio-Cierre-Salomon-Polar-LT-Urbano-Invierno-Hombre-Black-18040.jpg?v=638197541414570000",
        type: "sweatshirt",
        active: true,
    },
    {
        name: "GORRO BEANIE QUIKSILVER ROUTINE UNISEX",
        price: 10999,
        // rating: [3],
        brand: "Quiksilver",
        gender: "male",
        size: "Unique",
        //shoeSize: 38,
        color: "green",
        // comments: ["Compraría 1000", "Son excelentes"],
        stock: 10,
        image: "https://universoventura.vteximg.com.br/arquivos/ids/204594-600-600/Gorro-Beanie-Quiksilver-Routine-Ski-Snowboard-Unisex-Verde-Militar-2232140007.jpg?v=638222032887170000",
        type: "accesories",
        active: true,
    },
    {
        name: "ZAPATILLA FIRECAMP SLEDDER II WATERPROOF TREKKING",
        price: 65000,
        rating: [3],
        brand: "Columbia",
        gender: "female",
        // size: "M",
        shoeSize: 38,
        color: "grey",
        // comments: ["Compraría 1000", "Son excelentes"],
        stock: 6,
        image: "https://universoventura.vteximg.com.br/arquivos/ids/182101-600-600/Zapatilla-Firecamp-Sledder-II-Waterproof-Trekking-Ni%C3%B1a-BY2732-088-2.jpg?v=637237839009030000",
        type: "shoes",
        active: true,
    },
    {
        name: "REMERA LYCRA MANGA CORTA QUIKSILVER ALL TIMES PROTECCION UV 50+",
        price: 7300,
        // rating: [3],
        brand: "Quicksilver",
        gender: "male",
        size: "Unique",
        // shoeSize: 38,
        color: "pink",
        // comments: ["Compraría 1000", "Son excelentes"],
        stock: 1,
        image: "https://showsport.vtexassets.com/arquivos/ids/796632-300-auto?v=638173556143470000&width=300&height=auto&aspect=true",
        type: "accesories",
        active: true,
    },
    {
        name: "PANTALON ANSILTA CONGO 4 ",
        price: 48300,
        rating: [3],
        brand: "Ansilta",
        gender: "female",
        size: "M",
        // shoeSize: 38,
        color: "blue",
        comments: ["Buenos pantalones, la tela es super resistente"],
        stock: 10,
        image: "https://universoventura.vteximg.com.br/arquivos/ids/199478-600-600/Pantalon-Ansilta-Congo-4-Trekking-Hiking-Mujer-Petroleo-161529-371.jpg?v=638064710562030000",
        type: "pant",
        active: true,
    },
    {
        name: "LENTES DE SOL JULBO CAMINO CATEGORIA 3 VIOLET ROSE",
        price: 35720,
        // rating: [3],
        brand: "Julbo",
        gender: "female",
        size: "Unique",
        // shoeSize: 38,
        color: "pink",
        // comments: ["Compraría 1000", "Son excelentes"],
        stock: 1,
        image: "https://universoventura.vteximg.com.br/arquivos/ids/202562-600-600/Lentes-de-Sol-Julbo-Camino-Trekking-Categoria-3-Violet-Rose-J5011146-1.jpg?v=638175951520730000",
        type: "accesories",
        active: true,
    },
    {
        name: "Botas de mujer Glacier",
        price: 35890,
        // rating: [3],
        brand: "Glacier",
        gender: "female",
        // size: "Unique",
        shoeSize: 39,
        color: "orange",
        // comments: ["Compraría 1000", "Son excelentes"],
        stock: 1,
        image: "https://d368r8jqz0fwvm.cloudfront.net/41283-product_lg/botas-de-mujer-glacier.jpg",
        type: "shoes",
        active: true,
    },
    {
        name: "Campera de hombre Ewing Tec",
        price: 45200,
        // rating: [3],
        brand: "Montagne",
        gender: "male",
        size: "X",
        //shoeSize: 39,
        color: "green",
        // comments: ["Compraría 1000", "Son excelentes"],
        stock: 15,
        image: "https://d368r8jqz0fwvm.cloudfront.net/17856-product_lg/campera-de-hombre-ewing.jpg",
        type: "jacket",
        active: true,
    },
    {
        name: "LENTES ANTEOJOS RUSTY THE MAKER POLARIZADO - BLACK",
        price: 24100,
        rating: [5],
        brand: "Rusty",
        gender: "male",
        size: "Unique",
        //shoeSize: 39,
        color: "black",
        // comments: ["Compraría 1000", "Son excelentes"],
        stock: 8,
        image: "https://universoventura.vteximg.com.br/arquivos/ids/199791-600-600/Lentes-Anteojos-Rusty-the-Maker-Unisex-Polarized-MBLK-S10-Black-103485.jpg?v=638079168207300000",
        type: "accesories",
        active: true,
    }
]

export default articlesData;